name: Trigger auto deployment for container-app-gnpilp7jfwexo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-gnpilp7jfwexo-AutoDeployTrigger-822d5f17-2aa9-4c35-b939-83e9e9f9252b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGNPILP7JFWEXO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGNPILP7JFWEXO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGNPILP7JFWEXO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPGNPILP7JFWEXO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGNPILP7JFWEXO_REGISTRY_PASSWORD }}
          containerAppName: container-app-gnpilp7jfwexo
          resourceGroup: todonodejspgsqlgoogleauthb42986c6
          imageToBuild: default/container-app-gnpilp7jfwexo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


